/** Declaration file generated by dts-gen */

export function install(t: any): void;

export function mapWaitingActions(t: any, n: any, ...args: any[]): any;

export function mapWaitingGetters(t: any): any;

export function waitFor(t: any, n: any, ...args: any[]): any;

export namespace install {
    const prototype: {
    };

}

export namespace mapWaitingActions {
    const prototype: {
    };

}

export namespace mapWaitingGetters {
    const prototype: {
    };

}

export namespace waitFor {
    const prototype: {
    };

}

